name: "Bin Collection Schedule - Simbio v1"
version: "1.1.62"
slug: "bin_collection_simbiov1"
description: "Displays waste collection schedule for your address - Simbio mode"
url: "http://homeassistant.local:8123/hassio/dashboard"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  8081/tcp: 8081
ports_description:
  8081/tcp: Web interface
webui: "http://[HOST]:[PORT:8081]/"
init: false
map:
  - config:rw
options:
  address: "začret 69"
schema:
  address: str
