name: "Bin Collection Schedule - Simbio v1"
version: "2.0.0"
slug: "bin_collection_simbiov1"
description: "Displays waste collection schedule for your address - Simbio mode"
url: "http://homeassistant.local:8123/hassio/dashboard"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports: 
  "8081/tcp": null  # This makes the port dynamic and configurable
ports_description:
  "8081/tcp": "Web interface (configurable in options)"
webui: "http://[HOST]:[PORT:8081]/"
init: false
map:
  - "ssl"
  - "config:rw"
map_additional:
  - "/share/waste_collection/logs:/logs"
options:
  address: "POLJSKA POT 6, LJUBEČNA"
  port: 8081  # Default port
schema:
  address: str
  port: port  # This validates that the input is a valid port number
environment:
  LOG_FILE: "/tmp/waste_collection.log"
hassio_api: true